sudo: required
language: java
services:
- docker
after_success:
- MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive
  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- export REPO=enkelbr/enkel-circuit-breaker
- export TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo
  ${TRAVIS_BRANCH} ; fi`
- docker build -f Dockerfile --build-arg sb_jar=target/enkel-circuit-breaker-${MVN_VERSION}.jar
  -t ${REPO}:${TRAVIS_COMMIT::8} .
- docker tag ${REPO}:${TRAVIS_COMMIT::8} ${REPO}:${TAG}
- docker tag ${REPO}:${TRAVIS_COMMIT::8} ${REPO}:travis-${TRAVIS_BUILD_NUMBER}
- docker push ${REPO}